# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]}
  )', __dir__]).strip

platform :ios, min_ios_version_supported

# FIX non-modular include issues
use_modular_headers!

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SwappIos' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'GoogleMaps', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        build_config.build_settings['SWIFT_VERSION'] = '5.0'
        build_config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        # NUCLEAR FIX: Remove RCT_NEW_ARCH_ENABLED=1 from ALL pods.
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].reject! { |s| s == 'RCT_NEW_ARCH_ENABLED=1' }
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=0'

        # Fix for RN 0.74+ headers containing C++ code
        if target.name == 'ChargebeeReactNative'
          build_config.build_settings['SWIFT_OBJC_INTEROP_MODE'] = 'objcxx'
          build_config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-x' << 'objective-c++'
        end

        if target.name == 'Auth0' || target.name == 'A0Auth0'
          build_config.build_settings['SWIFT_VERSION'] = '5'
          build_config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        end
      end
    end
  end
end