// Workout Action Types
export const WORKOUT_GET_EXERCISES_REQUEST = 'WORKOUT_GET_EXERCISES_REQUEST';
export const WORKOUT_GET_EXERCISES_SUCCESS = 'WORKOUT_GET_EXERCISES_SUCCESS';
export const WORKOUT_GET_EXERCISES_FAILURE = 'WORKOUT_GET_EXERCISES_FAILURE';
export const WORKOUT_SET_SELECTED_FILTERS = 'WORKOUT_SET_SELECTED_FILTERS';
export const WORKOUT_CLEAR_SELECTED_FILTERS = 'WORKOUT_CLEAR_SELECTED_FILTERS';
export const WORKOUT_GET_BODY_PARTS_REQUEST = 'WORKOUT_GET_BODY_PARTS_REQUEST';
export const WORKOUT_GET_BODY_PARTS_SUCCESS = 'WORKOUT_GET_BODY_PARTS_SUCCESS';
export const WORKOUT_GET_BODY_PARTS_FAILURE = 'WORKOUT_GET_BODY_PARTS_FAILURE';

export const WORKOUT_GET_MUSCLES_REQUEST = 'WORKOUT_GET_MUSCLES_REQUEST';
export const WORKOUT_GET_MUSCLES_SUCCESS = 'WORKOUT_GET_MUSCLES_SUCCESS';
export const WORKOUT_GET_MUSCLES_FAILURE = 'WORKOUT_GET_MUSCLES_FAILURE';

export const WORKOUT_GET_EQUIPMENTS_REQUEST = 'WORKOUT_GET_EQUIPMENTS_REQUEST';
export const WORKOUT_GET_EQUIPMENTS_SUCCESS = 'WORKOUT_GET_EQUIPMENTS_SUCCESS';
export const WORKOUT_GET_EQUIPMENTS_FAILURE = 'WORKOUT_GET_EQUIPMENTS_FAILURE';

export const WORKOUT_LOG_SESSION_REQUEST = 'WORKOUT_LOG_SESSION_REQUEST';
export const WORKOUT_LOG_SESSION_SUCCESS = 'WORKOUT_LOG_SESSION_SUCCESS';
export const WORKOUT_LOG_SESSION_FAILURE = 'WORKOUT_LOG_SESSION_FAILURE';
export const WORKOUT_DELETE_SESSION_REQUEST = 'WORKOUT_DELETE_SESSION_REQUEST';
export const WORKOUT_DELETE_SESSION_SUCCESS = 'WORKOUT_DELETE_SESSION_SUCCESS';
export const WORKOUT_DELETE_SESSION_FAILURE = 'WORKOUT_DELETE_SESSION_FAILURE';
export const WORKOUT_DELETE_EXERCISE_REQUEST = 'WORKOUT_DELETE_EXERCISE_REQUEST';
export const WORKOUT_DELETE_EXERCISE_SUCCESS = 'WORKOUT_DELETE_EXERCISE_SUCCESS';
export const WORKOUT_DELETE_EXERCISE_FAILURE = 'WORKOUT_DELETE_EXERCISE_FAILURE';

// Diet Action Types
export const DIET_SAVE_ENTRY_REQUEST = 'DIET_SAVE_ENTRY_REQUEST';
export const DIET_SAVE_ENTRY_SUCCESS = 'DIET_SAVE_ENTRY_SUCCESS';
export const DIET_SAVE_ENTRY_FAILURE = 'DIET_SAVE_ENTRY_FAILURE';
export const DIET_UPDATE_LOG_REQUEST = 'DIET_UPDATE_LOG_REQUEST';
export const DIET_UPDATE_LOG_SUCCESS = 'DIET_UPDATE_LOG_SUCCESS';
export const DIET_UPDATE_LOG_FAILURE = 'DIET_UPDATE_LOG_FAILURE';
export const DIET_GET_LOGS_BY_DATE_REQUEST = 'DIET_GET_LOGS_BY_DATE_REQUEST';
export const DIET_GET_LOGS_BY_DATE_SUCCESS = 'DIET_GET_LOGS_BY_DATE_SUCCESS';
export const DIET_GET_LOGS_BY_DATE_FAILURE = 'DIET_GET_LOGS_BY_DATE_FAILURE';
export const DIET_DELETE_LOG_REQUEST = 'DIET_DELETE_LOG_REQUEST';
export const DIET_DELETE_LOG_SUCCESS = 'DIET_DELETE_LOG_SUCCESS';
export const DIET_DELETE_LOG_FAILURE = 'DIET_DELETE_LOG_FAILURE';

// Chat Action Types
export const CHAT_START_CONVERSATION_REQUEST = 'CHAT_START_CONVERSATION_REQUEST';
export const CHAT_START_CONVERSATION_SUCCESS = 'CHAT_START_CONVERSATION_SUCCESS';
export const CHAT_START_CONVERSATION_FAILURE = 'CHAT_START_CONVERSATION_FAILURE';
export const CHAT_GET_CONVERSATIONS_REQUEST = 'CHAT_GET_CONVERSATIONS_REQUEST';
export const CHAT_GET_CONVERSATIONS_SUCCESS = 'CHAT_GET_CONVERSATIONS_SUCCESS';
export const CHAT_GET_CONVERSATIONS_FAILURE = 'CHAT_GET_CONVERSATIONS_FAILURE';
export const CHAT_GET_MESSAGES_REQUEST = 'CHAT_GET_MESSAGES_REQUEST';
export const CHAT_GET_MESSAGES_SUCCESS = 'CHAT_GET_MESSAGES_SUCCESS';
export const CHAT_GET_MESSAGES_FAILURE = 'CHAT_GET_MESSAGES_FAILURE';
export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAILURE = 'CHAT_SEND_MESSAGE_FAILURE';

// Cart Action Types
export const CART_FETCH_REQUEST = 'CART_FETCH_REQUEST';
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
export const CART_FETCH_FAILURE = 'CART_FETCH_FAILURE';
export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAILURE = 'CART_ADD_ITEM_FAILURE';
export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST';
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS';
export const CART_UPDATE_ITEM_FAILURE = 'CART_UPDATE_ITEM_FAILURE';
export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';
export const CART_REMOVE_ITEM_FAILURE = 'CART_REMOVE_ITEM_FAILURE';
export const CART_CREATE_CHECKOUT_REQUEST = 'CART_CREATE_CHECKOUT_REQUEST';
export const CART_CREATE_CHECKOUT_SUCCESS = 'CART_CREATE_CHECKOUT_SUCCESS';
export const CART_CREATE_CHECKOUT_FAILURE = 'CART_CREATE_CHECKOUT_FAILURE';

// MultiProvider Action Types
export const MULTI_PROVIDER_GET_ALL_REQUEST = 'MULTI_PROVIDER_GET_ALL_REQUEST';
export const MULTI_PROVIDER_GET_ALL_SUCCESS = 'MULTI_PROVIDER_GET_ALL_SUCCESS';
export const MULTI_PROVIDER_GET_ALL_FAILURE = 'MULTI_PROVIDER_GET_ALL_FAILURE';
export const MULTI_PROVIDER_CHECK_IN_REQUEST = 'MULTI_PROVIDER_CHECK_IN_REQUEST';
export const MULTI_PROVIDER_CHECK_IN_SUCCESS = 'MULTI_PROVIDER_CHECK_IN_SUCCESS';
export const MULTI_PROVIDER_CHECK_IN_FAILURE = 'MULTI_PROVIDER_CHECK_IN_FAILURE';
export const MULTI_PROVIDER_CHECK_OUT_REQUEST = 'MULTI_PROVIDER_CHECK_OUT_REQUEST';
export const MULTI_PROVIDER_CHECK_OUT_SUCCESS = 'MULTI_PROVIDER_CHECK_OUT_SUCCESS';
export const MULTI_PROVIDER_CHECK_OUT_FAILURE = 'MULTI_PROVIDER_CHECK_OUT_FAILURE';
export const MULTI_PROVIDER_GET_HISTORY_REQUEST = 'MULTI_PROVIDER_GET_HISTORY_REQUEST';
export const MULTI_PROVIDER_GET_HISTORY_SUCCESS = 'MULTI_PROVIDER_GET_HISTORY_SUCCESS';
export const MULTI_PROVIDER_GET_HISTORY_FAILURE = 'MULTI_PROVIDER_GET_HISTORY_FAILURE';

// Profile Action Types
export const PROFILE_GET_USER_REQUEST = 'PROFILE_GET_USER_REQUEST';
export const PROFILE_GET_USER_SUCCESS = 'PROFILE_GET_USER_SUCCESS';
export const PROFILE_GET_USER_FAILURE = 'PROFILE_GET_USER_FAILURE';

// Providers Action Types
export const PROVIDERS_GET_BY_PLAN_IDS_REQUEST = 'PROVIDERS_GET_BY_PLAN_IDS_REQUEST';
export const PROVIDERS_GET_BY_PLAN_IDS_SUCCESS = 'PROVIDERS_GET_BY_PLAN_IDS_SUCCESS';
export const PROVIDERS_GET_BY_PLAN_IDS_FAILURE = 'PROVIDERS_GET_BY_PLAN_IDS_FAILURE';
export const PROVIDERS_CHECK_IN_REQUEST = 'PROVIDERS_CHECK_IN_REQUEST';
export const PROVIDERS_CHECK_IN_SUCCESS = 'PROVIDERS_CHECK_IN_SUCCESS';
export const PROVIDERS_CHECK_IN_FAILURE = 'PROVIDERS_CHECK_IN_FAILURE';
export const PROVIDERS_CHECK_OUT_REQUEST = 'PROVIDERS_CHECK_OUT_REQUEST';
export const PROVIDERS_CHECK_OUT_SUCCESS = 'PROVIDERS_CHECK_OUT_SUCCESS';
export const PROVIDERS_CHECK_OUT_FAILURE = 'PROVIDERS_CHECK_OUT_FAILURE';
export const PROVIDERS_GET_USER_CHECK_INS_REQUEST = 'PROVIDERS_GET_USER_CHECK_INS_REQUEST';
export const PROVIDERS_GET_USER_CHECK_INS_SUCCESS = 'PROVIDERS_GET_USER_CHECK_INS_SUCCESS';
export const PROVIDERS_GET_USER_CHECK_INS_FAILURE = 'PROVIDERS_GET_USER_CHECK_INS_FAILURE';
export const PROVIDERS_DISCOVER_REQUEST = 'PROVIDERS_DISCOVER_REQUEST';
export const PROVIDERS_DISCOVER_SUCCESS = 'PROVIDERS_DISCOVER_SUCCESS';
export const PROVIDERS_DISCOVER_FAILURE = 'PROVIDERS_DISCOVER_FAILURE';
export const PROVIDERS_GET_DETAILS_REQUEST = 'PROVIDERS_GET_DETAILS_REQUEST';
export const PROVIDERS_GET_DETAILS_SUCCESS = 'PROVIDERS_GET_DETAILS_SUCCESS';
export const PROVIDERS_GET_DETAILS_FAILURE = 'PROVIDERS_GET_DETAILS_FAILURE';

// Notification Action Types
export const NOTIFICATION_GET_USER_REQUEST = 'NOTIFICATION_GET_USER_REQUEST';
export const NOTIFICATION_GET_USER_SUCCESS = 'NOTIFICATION_GET_USER_SUCCESS';
export const NOTIFICATION_GET_USER_FAILURE = 'NOTIFICATION_GET_USER_FAILURE';
export const NOTIFICATION_MARK_READ_REQUEST = 'NOTIFICATION_MARK_READ_REQUEST';
export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS';
export const NOTIFICATION_MARK_READ_FAILURE = 'NOTIFICATION_MARK_READ_FAILURE';
export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAILURE = 'NOTIFICATION_DELETE_FAILURE';

// Trainer Action Types
export const TRAINER_GET_BY_PLAN_IDS_REQUEST = 'TRAINER_GET_BY_PLAN_IDS_REQUEST';
export const TRAINER_GET_BY_PLAN_IDS_SUCCESS = 'TRAINER_GET_BY_PLAN_IDS_SUCCESS';
export const TRAINER_GET_BY_PLAN_IDS_FAILURE = 'TRAINER_GET_BY_PLAN_IDS_FAILURE';
export const TRAINER_START_CONVERSATION_REQUEST = 'TRAINER_START_CONVERSATION_REQUEST';
export const TRAINER_START_CONVERSATION_SUCCESS = 'TRAINER_START_CONVERSATION_SUCCESS';
export const TRAINER_START_CONVERSATION_FAILURE = 'TRAINER_START_CONVERSATION_FAILURE';
export const TRAINER_BROWSE_REQUEST = 'TRAINER_BROWSE_REQUEST';
export const TRAINER_BROWSE_SUCCESS = 'TRAINER_BROWSE_SUCCESS';
export const TRAINER_BROWSE_FAILURE = 'TRAINER_BROWSE_FAILURE';
export const TRAINER_GET_BY_ID_REQUEST = 'TRAINER_GET_BY_ID_REQUEST';
export const TRAINER_GET_BY_ID_SUCCESS = 'TRAINER_GET_BY_ID_SUCCESS';
export const TRAINER_GET_BY_ID_FAILURE = 'TRAINER_GET_BY_ID_FAILURE';
export const TRAINER_GET_BY_TRAINER_ID_REQUEST = 'TRAINER_GET_BY_TRAINER_ID_REQUEST';
export const TRAINER_GET_BY_TRAINER_ID_SUCCESS = 'TRAINER_GET_BY_TRAINER_ID_SUCCESS';
export const TRAINER_GET_BY_TRAINER_ID_FAILURE = 'TRAINER_GET_BY_TRAINER_ID_FAILURE';

// Post Action Types
export const POST_GET_ALL_REQUEST = 'POST_GET_ALL_REQUEST';
export const POST_GET_ALL_SUCCESS = 'POST_GET_ALL_SUCCESS';
export const POST_GET_ALL_FAILURE = 'POST_GET_ALL_FAILURE';
export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE';
export const POST_ADD_COMMENT_REQUEST = 'POST_ADD_COMMENT_REQUEST';
export const POST_ADD_COMMENT_SUCCESS = 'POST_ADD_COMMENT_SUCCESS';
export const POST_ADD_COMMENT_FAILURE = 'POST_ADD_COMMENT_FAILURE';
export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAILURE = 'POST_LIKE_FAILURE';

// Subscription Action Types
export const SUBSCRIPTION_CREATE_CHECKOUT_REQUEST = 'SUBSCRIPTION_CREATE_CHECKOUT_REQUEST';
export const SUBSCRIPTION_CREATE_CHECKOUT_SUCCESS = 'SUBSCRIPTION_CREATE_CHECKOUT_SUCCESS';
export const SUBSCRIPTION_CREATE_CHECKOUT_FAILURE = 'SUBSCRIPTION_CREATE_CHECKOUT_FAILURE';
export const SUBSCRIPTION_CREATE_PORTAL_REQUEST = 'SUBSCRIPTION_CREATE_PORTAL_REQUEST';
export const SUBSCRIPTION_CREATE_PORTAL_SUCCESS = 'SUBSCRIPTION_CREATE_PORTAL_SUCCESS';
export const SUBSCRIPTION_CREATE_PORTAL_FAILURE = 'SUBSCRIPTION_CREATE_PORTAL_FAILURE';
export const SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_REQUEST = 'SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_REQUEST';
export const SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_SUCCESS = 'SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_SUCCESS';
export const SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_FAILURE = 'SUBSCRIPTION_GET_MULTI_PROVIDER_TIERS_FAILURE';

// Shop Action Types
export const SHOP_FETCH_PRODUCTS_REQUEST = 'SHOP_FETCH_PRODUCTS_REQUEST';
export const SHOP_FETCH_PRODUCTS_SUCCESS = 'SHOP_FETCH_PRODUCTS_SUCCESS';
export const SHOP_FETCH_PRODUCTS_FAILURE = 'SHOP_FETCH_PRODUCTS_FAILURE';

// Home Action Types
export const HOME_GET_FEED_REQUEST = 'HOME_GET_FEED_REQUEST';
export const HOME_GET_FEED_SUCCESS = 'HOME_GET_FEED_SUCCESS';
export const HOME_GET_FEED_FAILURE = 'HOME_GET_FEED_FAILURE';
